#!/bin/zsh

function zle-keymap-select {
    VIMODE="${${KEYMAP/vicmd/-- COMMAND --}/(main|viins)/}"
    zle reset-prompt
}

function accept_line {
    VIMODE=""
    builtin zle .accept-line
}

zle -N zle-keymap-select
zle -N accept_line

bindkey -a "^M" accept_line

setprompt () {
    setopt prompt_subst
    autoload colors
    colors

    PROMPT='%{${fg[red]}%}/--(%{${fg[yellow]}%}%n@%M%{${fg[red]}%})--(%{${fg[yellow]}%}%/%{${fg[red]}%})
%{${fg[red]}%}\--(%{${fg[yellow]}%}%B%1~%b%{${fg[red]}%})--> %{${fg[yellow]}%}%# %{${fg[white]}%}'
    RPROMPT='%{${fg[yellow]}%}${VIMODE}%{${fg[white]}%}'
}

setprompt
