#!/bin/bash

alias sudo='sudo '
alias die='sudo systemctl poweroff'

alias m=". m.sh"

alias vim='gvim --servername GVIM --remote-silent-tab'

alias ls='ls -X --color=auto --group-directories-first'
alias la='ls -AX --color=auto --group-directories-first'
alias ll='ls -lX --color=auto --group-directories-first'
alias lla='ls -lAX --color=auto --group-directories-first'

alias grep='grep --color=auto'

alias pacsys-update='pacman -Syyu'
alias pacfind='pacman -Ss'
alias pacinstall='pacman -S'
alias pacremove='pacman -R'

alias pacmirror-update='reflector -l 8 --sort rate --save /etc/pacman.d/mirrorlist'

# TEMPORÄR!!!
alias ds='xrandr --output LVDS1 --off; sleep 1; xrandr --output VGA1 --auto'

alias cb='cd /home/laurin/Documents/Basispruefung/'
alias moba='. /home/laurin/.shellscripts/moba'
alias umoba='. /home/laurin/.shellscripts/umoba'

#WINE


alias banana70='wine /home/laurin/.wine/drive_c/Program\ Files\ (x86)/Banana70/Banana70.exe'
