#!/bin/bash

state=$(amixer -c 0 get Master playback | grep Mono: | awk -F[ '{print $2}' | awk -F% '{print $1}')

if [ $state = 0 ] ; then
  echo "VOL $state%";
else 
  echo "<fc=black,red> VOL $state% </fc>";
fi
